// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zndnonyaolxzpxjqlvfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZG5vbnlhb2x4enB4anFsdmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTk0MjIsImV4cCI6MjA1NjE5NTQyMn0._oHFe0zXwNwvtBbhExQ4WdHdjWYdFdFUeNoVHcBb2Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);